# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqquser',
            name='creae_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
