# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-08 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190408_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='creae_time',
            new_name='create_time',
        ),
    ]
